name       : pygal
version    : 2.4.0
release    : 2
source     :
    - https://github.com/Kozea/pygal/archive/2.4.0.tar.gz : 16d29d72abc2e2bd5e296a68e62b5b98d797385295084eb7853fd4e221b471f7
license    : LGPL-3.0
component  : programming.python
summary    : PYthon svg GrAph plotting Library
description: |
    PYthon svg GrAph plotting Library
builddeps  :
    - python-setuptools
    - pytest-runner
build      : |
    %python3_setup
install    : |
    %python3_install
