name       : pygal
version    : 3.0.0
release    : 5
source     :
    - https://github.com/Kozea/pygal/archive/refs/tags/3.0.0.tar.gz : 3bcce2c8353d4b2b2a883490cc1bc50c971e5baca95fcee8ca8133b9c3f9fad6
homepage   : https://www.pygal.org/
license    : LGPL-3.0-or-later
component  : programming.python
summary    : PYthon svg GrAph plotting Library
description: |
    pygal is a dynamic SVG charting library written in python.
builddeps  :
    - pytest-runner # check
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    # require packaging python-pyquery
#    %python3_test
